[build.environment]
PYTHON_VERSION = "3.11.9"

[build]
  command = "pip install -r requirements.txt && python main.py"
  publish = "static"  # If you have static files in the 'static' directory

[dev]
  command = "python main.py"  # Ensure that Netlify knows how to run your app locally
  port = 8888  # Set the appropriate port for local development
